[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "feature/add-logging-level"
  source = "github.com/shawn-hurley/operator-sdk"
  # version = "=v0.0.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.1"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  source = "github.com/shawn-hurley/controller-runtime"
  branch = "unstructured"
#  version = "v0.1.1"

[prune]
  go-tests = true
  unused-packages = true
