---
# tasks file for busybox
- name: start busybox
  k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ meta.name }}-busybox'
        namespace: '{{ meta.namespace }}'
      spec:
        selector:
          matchLabels:
            app: test
        template:
          metadata:
            labels:
              app: test
          spec:
            containers:
            - name: test
              image: "busybox"
              command: ["/bin/sh"]
              args: ["-c", "while true; do echo {{ message|quote }}; sleep {{ echo_delay | int }} ;done"]
